import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.scss'





const roboto = Roboto({
  weight: ['500','700'],
  subsets: ['latin'],
})

import styles from "./page.module.scss";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main >{children}</main>
        <Footer />
      </body>
    </html>
  );
}
